### ISSUE TITLE
Possible broken stylesheet across other browsers

### ISSUE THREAD

**Issue by EnKrypt** [workframecode/workfra.me#1]
Referencing [this line of code](https://github.com/workframecode/workfra.me/blob/e165d1f921c26409332529ce55dff3641c249c4a/html/css/style.css#L110)

Since the `<center>` tag is no longer supported according to w3c, I chose to remove it, but simply replacing it with a div with `text-align: center` and `margin: 0 auto` did not work. So investigating further, I discovered that the css rule that kept my elements within the `<center>` tag centered was actually `text-align: -webkit-center`.

Interestingly this means that this webkit specific vendor rule did not behave in the same way as simply doing `text-align: center` and I could not find another alternative.

Since removing that webkit rule breaks the alignment, I'm concerned that other non-webkit browsers like Firefox or Edge are displaying it broken as well. Requesting others to confirm this issue by testing with different browsers.

Browser I've tried with : Google Chrome  
How to test : Check if the recaptcha badge at the bottom of the page is centered horizontally or not.

**Comment by adithyakreddy** [comment]
Eh?

**Comment by adithyakreddy** [comment]
Fixed https://github.com/workframecode/workfra.me/commit/bbae4e8
